---
- name: "Download Elasticsearch's rpm"
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
    dest: "/tmp/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
  register: download_elastic
  until: download_elastic is succeeded
- name: Install Elasticsearch
  become: true
  yum:
    name: "/tmp/elasticsearch-{{ elasticsearch_version }}-x86_64.rpm"
    state: present
  notify: restart Elasticsearch